services:
#    spoiled_car_front_office.example:
#        class: SpoiledCar\FrontOfficeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    authentication.handler.login_success_handler:
        class:  FOS\UserBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']
