SpoiledCar\FrontOfficeBundle\Entity\Interventions:
    type: entity
    table: interventions
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        interventions:
            type: string
            nullable: false
            length: 255
            fixed: false
        step:
            type: integer
            nullable: false
            unsigned: false
    lifecycleCallbacks: {  }



