<?php

namespace SpoiledCar\FrontOfficeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Intervention_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Intervention_UserRepository extends EntityRepository
{
}
